version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_weather
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  weather-backend:
    image: weather-backend
    env_file:
      - server/.env
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - mongodb
    networks:
      - app-network

  weather-frontend:
    image: weather-frontend
    env_file:
      - client/.env
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - weather-backend
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
